configuration:
  store: "in_memory"
  use_algo: "token_bucket"
  algo_settings:
    capacity: 10
    rate: 0.5 # Per second
#  token_bucket:
#    capacity: 100
#    rate: 20 # Per second
#  fixed_window:
#    window_size: "100s"
#    max_requests: 100
#  rolling_window:
#    window_size: "100s"
#    TTL: "60s"
#    max_requests: 1000
#    min_interval: "0.5s"
#  rolling_window_extra_identication:
#    window_size: "100s"
#    TTL: "60s"
#    max_requests: 1000
#    min_interval: "0.5s"